use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

use super::analyzer::{OutcomeType, SessionOutcome, ToolResultType};
use super::store::EvolutionStore;

/// Where a generated rule came from.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum RuleSource {
    OrderingPattern,
    RepeatedFailure,
    ProjectPattern,
}

impl RuleSource {
    pub fn to_db_string(&self) -> &'static str {
        match self {
            RuleSource::OrderingPattern => "ordering",
            RuleSource::RepeatedFailure => "failure",
            RuleSource::ProjectPattern => "project",
        }
    }

    pub fn from_db_string(s: &str) -> Self {
        match s {
            "ordering" => RuleSource::OrderingPattern,
            "failure" => RuleSource::RepeatedFailure,
            "project" => RuleSource::ProjectPattern,
            _ => RuleSource::OrderingPattern,
        }
    }
}

/// A rule generated by the evolution engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedRule {
    pub name: String,
    pub source: RuleSource,
    /// Confidence score in [0.0, 1.0].
    pub confidence: f64,
    /// The FTAI Rules DSL text for this rule.
    pub ftai_rule: String,
}

/// Minimum observations required before generating a rule from a pattern.
const MIN_OBSERVATIONS: usize = 5;
/// Minimum success rate to consider a pattern worth codifying.
const MIN_SUCCESS_RATE: f64 = 0.8;
/// Maximum number of active evolution rules.
const MAX_ACTIVE_RULES: usize = 20;

/// The evolution engine: analyzes session outcomes to generate FTAI rules.
pub struct EvolutionEngine {
    store: EvolutionStore,
    /// Minimum sessions before attempting pattern detection.
    min_sessions: usize,
}

impl EvolutionEngine {
    pub fn new(store: EvolutionStore) -> Self {
        Self {
            store,
            min_sessions: 3,
        }
    }

    #[cfg(test)]
    pub fn with_min_sessions(store: EvolutionStore, min_sessions: usize) -> Self {
        Self {
            store,
            min_sessions,
        }
    }

    /// Save the outcome and, if enough data has accumulated, detect patterns
    /// and return any newly generated rules.
    pub fn analyze_and_evolve(&self, outcome: &SessionOutcome) -> Result<Vec<GeneratedRule>> {
        self.store.save_outcome(outcome)?;

        // Auto-disable ineffective rules.
        let to_disable = self.store.check_auto_disable()?;
        for name in &to_disable {
            self.store.disable_rule(name)?;
        }

        let count = self.store.session_count()?;
        if count < self.min_sessions {
            return Ok(vec![]);
        }

        // Check active rule count before generating more.
        let active_count = self.store.active_rules()?.len();
        if active_count >= MAX_ACTIVE_RULES {
            return Ok(vec![]);
        }

        let sessions = self.store.recent_sessions(50)?;
        let mut generated = Vec::new();

        let budget = MAX_ACTIVE_RULES.saturating_sub(active_count);

        generated.extend(self.detect_ordering_patterns(&sessions));
        generated.extend(self.detect_repeated_failures(&sessions));
        generated.extend(self.detect_project_patterns(&outcome.project, &sessions));

        generated.truncate(budget);

        for rule in &generated {
            self.store.save_generated_rule(rule)?;
        }

        Ok(generated)
    }

    /// Find tool call orderings that correlate with success.
    ///
    /// Example: if `file_read` before `file_edit` succeeds 80%+ of the time,
    /// generate a rule recommending that ordering.
    fn detect_ordering_patterns(&self, sessions: &[SessionOutcome]) -> Vec<GeneratedRule> {
        // Count (tool_a -> tool_b) pair outcomes.
        let mut pair_stats: HashMap<(String, String), (usize, usize)> = HashMap::new(); // (successes, total)

        for session in sessions {
            let is_success = session.success.is_success();
            // Look at consecutive pairs.
            for window in session.tool_calls.windows(2) {
                let a = &window[0].tool_name;
                let b = &window[1].tool_name;
                if a == b {
                    continue;
                }
                let entry = pair_stats.entry((a.clone(), b.clone())).or_insert((0, 0));
                entry.1 += 1;
                if is_success {
                    entry.0 += 1;
                }
            }
        }

        let mut rules = Vec::new();
        for ((a, b), (successes, total)) in &pair_stats {
            if *total < MIN_OBSERVATIONS {
                continue;
            }
            let rate = *successes as f64 / *total as f64;
            if rate < MIN_SUCCESS_RATE {
                continue;
            }
            let safe_a = sanitize_for_dsl(a);
            let safe_b = sanitize_for_dsl(b);
            let name = format!("evo-order-{safe_a}-before-{safe_b}");
            let ftai_rule = format!(
                "rule {name} {{\n  scope \"*\"\n  on tool_call\n  when sequence(\"{safe_a}\", \"{safe_b}\")\n  # Auto-generated: {safe_a} before {safe_b} succeeds {:.0}% of the time ({} observations)\n}}",
                rate * 100.0,
                total
            );
            rules.push(GeneratedRule {
                name,
                source: RuleSource::OrderingPattern,
                confidence: rate,
                ftai_rule,
            });
        }
        rules
    }

    /// Find tools that fail repeatedly with similar error patterns.
    fn detect_repeated_failures(&self, sessions: &[SessionOutcome]) -> Vec<GeneratedRule> {
        // Aggregate failure counts per tool.
        let mut failure_counts: HashMap<String, HashMap<String, usize>> = HashMap::new();
        let mut total_calls: HashMap<String, usize> = HashMap::new();

        for session in sessions {
            for tc in &session.tool_calls {
                *total_calls.entry(tc.tool_name.clone()).or_default() += 1;
                if let ToolResultType::Error(ref msg) = tc.result_type {
                    // Normalize: take first 80 chars as a key.
                    let key = if msg.len() > 80 {
                        msg[..80].to_string()
                    } else {
                        msg.clone()
                    };
                    *failure_counts
                        .entry(tc.tool_name.clone())
                        .or_default()
                        .entry(key)
                        .or_default() += 1;
                }
            }
        }

        let mut rules = Vec::new();
        for (tool, errors) in &failure_counts {
            let tool_total = total_calls.get(tool).copied().unwrap_or(0);
            for (error_pattern, count) in errors {
                if *count < MIN_OBSERVATIONS {
                    continue;
                }
                let failure_rate = *count as f64 / tool_total as f64;
                if failure_rate < 0.3 {
                    continue; // Only flag if this error is fairly common for this tool.
                }
                let safe_tool = sanitize_for_dsl(tool);
                let name = format!("evo-fail-{safe_tool}-{}", &sha_short(error_pattern));
                let escaped = escape_for_dsl_comment(error_pattern);
                let ftai_rule = format!(
                    "rule {name} {{\n  scope \"*\"\n  on tool_call\n  when tool(\"{safe_tool}\") && error_like(\"{escaped}\")\n  reject \"Repeated failure pattern: {escaped}\"\n  # Auto-generated: {count}/{tool_total} calls to {safe_tool} fail with this error\n}}"
                );
                rules.push(GeneratedRule {
                    name,
                    source: RuleSource::RepeatedFailure,
                    confidence: failure_rate.min(0.95),
                    ftai_rule,
                });
            }
        }
        rules
    }

    /// Detect patterns specific to a project.
    fn detect_project_patterns(
        &self,
        project: &str,
        sessions: &[SessionOutcome],
    ) -> Vec<GeneratedRule> {
        let project_sessions: Vec<&SessionOutcome> =
            sessions.iter().filter(|s| s.project == project).collect();

        if project_sessions.len() < MIN_OBSERVATIONS {
            return vec![];
        }

        // Detect if a particular tool dominates successful sessions in this project.
        let mut tool_success: HashMap<String, (usize, usize)> = HashMap::new(); // (in_success, total)
        for session in &project_sessions {
            let is_success = session.success.is_success();
            let tools_used: std::collections::HashSet<&str> = session
                .tool_calls
                .iter()
                .map(|tc| tc.tool_name.as_str())
                .collect();
            for tool in tools_used {
                let entry = tool_success.entry(tool.to_string()).or_insert((0, 0));
                entry.1 += 1;
                if is_success {
                    entry.0 += 1;
                }
            }
        }

        let mut rules = Vec::new();
        for (tool, (successes, total)) in &tool_success {
            if *total < MIN_OBSERVATIONS {
                continue;
            }
            let rate = *successes as f64 / *total as f64;
            if rate < MIN_SUCCESS_RATE {
                continue;
            }
            // Only flag if the tool is used in most successful sessions.
            let success_count = project_sessions
                .iter()
                .filter(|s| s.success.is_success())
                .count();
            if success_count == 0 {
                continue;
            }
            let prevalence = *successes as f64 / success_count as f64;
            if prevalence < 0.7 {
                continue;
            }

            let safe_project = sanitize_for_dsl(project);
            let safe_tool = sanitize_for_dsl(tool);
            let name = format!("evo-project-{safe_project}-uses-{safe_tool}");
            let ftai_rule = format!(
                "rule {name} {{\n  scope \"{safe_project}\"\n  # Auto-generated: {safe_tool} is used in {:.0}% of successful sessions for {safe_project}\n}}",
                prevalence * 100.0
            );
            rules.push(GeneratedRule {
                name,
                source: RuleSource::ProjectPattern,
                confidence: rate * prevalence,
                ftai_rule,
            });
        }
        rules
    }
}

/// Sanitize a string for safe interpolation into FTAI DSL identifiers (rule names, tool names).
/// Strips any character that is not alphanumeric, underscore, or hyphen.
/// OWASP: A03:2021 Injection — prevents DSL injection via tool/rule names.
fn sanitize_for_dsl(input: &str) -> String {
    input.chars().filter(|c| c.is_ascii_alphanumeric() || *c == '_' || *c == '-').collect()
}

/// Escape a string for safe interpolation into a FTAI DSL comment or quoted string.
/// Handles backslash escape bypass, newline injection, brace injection, and truncates
/// to prevent oversized payloads in generated rules.
/// OWASP: A03:2021 Injection — prevents DSL injection via error messages.
fn escape_for_dsl_comment(input: &str) -> String {
    let mut s = input.replace('\\', "\\\\"); // Backslashes FIRST to avoid double-escaping
    s = s.replace('"', "\\\"");
    s = s.replace('\n', " ");
    s = s.replace('\r', " ");
    s = s.replace('{', " ");
    s = s.replace('}', " ");
    if s.len() > 200 {
        s.truncate(200);
    }
    s
}

/// Short hash for deduplication in rule names.
fn sha_short(s: &str) -> String {
    use sha2::{Digest, Sha256};
    let hash = Sha256::digest(s.as_bytes());
    format!("{:x}{:x}{:x}{:x}", hash[0], hash[1], hash[2], hash[3])
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::evolution::analyzer::*;
    use tempfile::NamedTempFile;

    fn make_store() -> EvolutionStore {
        let tmp = NamedTempFile::new().unwrap();
        EvolutionStore::open(tmp.path()).unwrap()
    }

    fn make_outcome(
        id: &str,
        project: &str,
        outcome: OutcomeType,
        tools: Vec<(&str, ToolResultType)>,
    ) -> SessionOutcome {
        SessionOutcome {
            session_id: id.to_string(),
            project: project.to_string(),
            timestamp: 1711500000,
            task_description: "task".to_string(),
            tool_calls: tools
                .into_iter()
                .map(|(name, result)| ToolCallRecord {
                    tool_name: name.to_string(),
                    arguments_summary: String::new(),
                    result_type: result,
                    duration_ms: 10,
                })
                .collect(),
            success: outcome,
            user_feedback: None,
            total_tokens: 1000,
            retries: 0,
        }
    }

    #[test]
    fn test_below_min_sessions_no_rules() {
        let store = make_store();
        let engine = EvolutionEngine::with_min_sessions(store, 10);

        let outcome = make_outcome(
            "s1",
            "proj",
            OutcomeType::Success,
            vec![("file_read", ToolResultType::Success)],
        );
        let rules = engine.analyze_and_evolve(&outcome).unwrap();
        assert!(rules.is_empty());
    }

    #[test]
    fn test_ordering_pattern_detection() {
        let store = make_store();
        let engine = EvolutionEngine::with_min_sessions(store, 1);

        // Create 6 sessions where file_read -> file_edit succeeds.
        for i in 0..6 {
            let outcome = make_outcome(
                &format!("s{i}"),
                "proj",
                OutcomeType::Success,
                vec![
                    ("file_read", ToolResultType::Success),
                    ("file_edit", ToolResultType::Success),
                ],
            );
            engine.analyze_and_evolve(&outcome).unwrap();
        }

        // The 6th call should have enough data to generate a rule.
        let outcome = make_outcome(
            "s-final",
            "proj",
            OutcomeType::Success,
            vec![
                ("file_read", ToolResultType::Success),
                ("file_edit", ToolResultType::Success),
            ],
        );
        let rules = engine.analyze_and_evolve(&outcome).unwrap();

        let ordering_rules: Vec<_> = rules
            .iter()
            .filter(|r| r.source == RuleSource::OrderingPattern)
            .collect();
        // Should have detected file_read -> file_edit pattern.
        assert!(
            ordering_rules
                .iter()
                .any(|r| r.name.contains("file_read") && r.name.contains("file_edit")),
            "Expected ordering rule for file_read->file_edit, got: {:?}",
            ordering_rules
        );
    }

    #[test]
    fn test_repeated_failure_detection() {
        let store = make_store();
        let engine = EvolutionEngine::with_min_sessions(store, 1);

        // Create sessions where bash consistently fails with the same error.
        for i in 0..6 {
            let outcome = make_outcome(
                &format!("fail-{i}"),
                "proj",
                OutcomeType::Failure("compile error".into()),
                vec![(
                    "bash",
                    ToolResultType::Error("permission denied: /etc/shadow".into()),
                )],
            );
            engine.analyze_and_evolve(&outcome).unwrap();
        }

        let outcome = make_outcome(
            "fail-final",
            "proj",
            OutcomeType::Failure("same".into()),
            vec![(
                "bash",
                ToolResultType::Error("permission denied: /etc/shadow".into()),
            )],
        );
        let rules = engine.analyze_and_evolve(&outcome).unwrap();
        let failure_rules: Vec<_> = rules
            .iter()
            .filter(|r| r.source == RuleSource::RepeatedFailure)
            .collect();
        assert!(
            !failure_rules.is_empty(),
            "Expected failure pattern rule for bash"
        );
    }

    #[test]
    fn test_threshold_not_met_no_rules() {
        let store = make_store();
        let engine = EvolutionEngine::with_min_sessions(store, 1);

        // Only 3 observations (below MIN_OBSERVATIONS of 5).
        for i in 0..3 {
            let outcome = make_outcome(
                &format!("s{i}"),
                "proj",
                OutcomeType::Success,
                vec![
                    ("grep", ToolResultType::Success),
                    ("file_edit", ToolResultType::Success),
                ],
            );
            engine.analyze_and_evolve(&outcome).unwrap();
        }

        let outcome = make_outcome(
            "s-check",
            "proj",
            OutcomeType::Success,
            vec![
                ("grep", ToolResultType::Success),
                ("file_edit", ToolResultType::Success),
            ],
        );
        let rules = engine.analyze_and_evolve(&outcome).unwrap();
        let ordering = rules
            .iter()
            .filter(|r| r.source == RuleSource::OrderingPattern)
            .count();
        assert_eq!(
            ordering, 0,
            "Should not generate rules below 5 observations"
        );
    }

    #[test]
    fn test_low_success_rate_no_rules() {
        let store = make_store();
        let engine = EvolutionEngine::with_min_sessions(store, 1);

        // 3 successes, 4 failures with same ordering = ~43% success rate, below 80%.
        for i in 0..3 {
            let outcome = make_outcome(
                &format!("ok-{i}"),
                "proj",
                OutcomeType::Success,
                vec![
                    ("glob", ToolResultType::Success),
                    ("file_write", ToolResultType::Success),
                ],
            );
            engine.analyze_and_evolve(&outcome).unwrap();
        }
        for i in 0..4 {
            let outcome = make_outcome(
                &format!("fail-{i}"),
                "proj",
                OutcomeType::Failure("err".into()),
                vec![
                    ("glob", ToolResultType::Success),
                    ("file_write", ToolResultType::Error("disk full".into())),
                ],
            );
            engine.analyze_and_evolve(&outcome).unwrap();
        }

        let outcome = make_outcome(
            "check",
            "proj",
            OutcomeType::Success,
            vec![
                ("glob", ToolResultType::Success),
                ("file_write", ToolResultType::Success),
            ],
        );
        let rules = engine.analyze_and_evolve(&outcome).unwrap();
        let ordering = rules
            .iter()
            .filter(|r| r.source == RuleSource::OrderingPattern && r.name.contains("glob"))
            .count();
        assert_eq!(
            ordering, 0,
            "Should not generate ordering rule at ~43% success rate"
        );
    }

    #[test]
    fn test_rule_source_roundtrip() {
        let sources = vec![
            RuleSource::OrderingPattern,
            RuleSource::RepeatedFailure,
            RuleSource::ProjectPattern,
        ];
        for src in sources {
            let s = src.to_db_string();
            let restored = RuleSource::from_db_string(s);
            assert_eq!(src, restored);
        }
    }

    #[test]
    fn test_generated_rule_has_ftai_syntax() {
        let store = make_store();
        let engine = EvolutionEngine::with_min_sessions(store, 1);

        for i in 0..7 {
            let outcome = make_outcome(
                &format!("s{i}"),
                "proj",
                OutcomeType::Success,
                vec![
                    ("file_read", ToolResultType::Success),
                    ("file_edit", ToolResultType::Success),
                ],
            );
            engine.analyze_and_evolve(&outcome).unwrap();
        }

        let rules = engine
            .analyze_and_evolve(&make_outcome(
                "final",
                "proj",
                OutcomeType::Success,
                vec![
                    ("file_read", ToolResultType::Success),
                    ("file_edit", ToolResultType::Success),
                ],
            ))
            .unwrap();

        for rule in &rules {
            assert!(
                rule.ftai_rule.contains("rule "),
                "Rule should contain 'rule' keyword"
            );
            assert!(
                rule.ftai_rule.contains('{'),
                "Rule should contain opening brace"
            );
            assert!(
                rule.ftai_rule.contains('}'),
                "Rule should contain closing brace"
            );
        }
    }
}
