pub mod backend;
pub mod config;
pub mod conversation;
pub mod dream;
#[cfg(feature = "evolution")]
pub mod evolution;
pub mod formatting;
pub mod hooks;
pub mod inference;
pub mod permissions;
pub mod plugins;
pub mod rules;
#[cfg(feature = "search")]
pub mod search;
pub mod session;
pub mod skills;
pub mod tools;
pub mod tui;
